services:
  app:
    build:
      context: ./docker/php
    container_name: task-app
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    environment:
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: "1"
    depends_on:
      - mysql
      - redis

  nginx:
    image: nginx:1.27-alpine
    container_name: task-nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: task-mysql
    environment:
      MYSQL_DATABASE: task_db
      MYSQL_USER: task_user
      MYSQL_PASSWORD: task_password
      MYSQL_ROOT_PASSWORD: delfi
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "4000:3306"

  redis:
    image: redis:7-alpine
    container_name: task-redis
    ports:
      - "6380:6379"

  node:
    image: node:20-alpine
    container_name: task-node
    working_dir: /var/www/html
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5173"
    volumes:
      - ./:/var/www/html
    ports:
      - "5173:5173"
    depends_on:
      - app

volumes:
  db-data:
